### ISSUE TITLE
Url parsing error

### ISSUE THREAD

**Issue by gorbypark** [beyondit/map-tiles-crawler#2]
I'm attempting to parse an url (ex: `http://url.com/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}`) and am getting an error 
```
/Users/gorbypark/Documents/Code/blah/node_modules/map-tiles-crawler/src/crawler.js:60
        target : targetPrefix + this.replacePath(path[0], tile)
                                                     ^

TypeError: Cannot read property '0' of null
```

Most likely it is because the url isn't in the standard {x}/{y}/{z}.jpeg format.  I had a look at the regexp matching function but to be honest I'm not exactly sure where to start trying to parse that long expression!  Any clues?

**Comment by stefanhuber** [comment]
You are right, the regex is quite limited. So your case would be like that `http://url.com/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}`?

**Comment by gorbypark** [comment]
> You are right, the regex is quite limited. So your case would be like that `http://url.com/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}`?

Yup, exactly.

**Comment by stefanhuber** [comment]
I updated the project: https://www.npmjs.com/package/map-tiles-crawler to version 1.0.2.
You have to add a `#.jpg` or what format you have at the end, otherwise there is no information, what files are downloaded...

So url like that: `http://url.com/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}#.jpeg`

**Comment by gorbypark** [comment]
> I updated the project: https://www.npmjs.com/package/map-tiles-crawler to version 1.0.2.
You're my hero, thanks!
